### ISSUE TITLE
Show validation errors

### ISSUE THREAD

**Issue by srgkm** [p1c2u/openapi-core#178] opened 2020-01-17 09:26 UTC
Is it possible to show validation errors for body? At the moment I've get to general exception with no detail about concrete property.

Schema.validate has "TODO: pass validation errors" :)  What is the easiest way to patch this?

Thanks

**Comment by p1c2u** [comment] 2020-01-21 09:25
Hi @srgkm 
it's already done in master. You can try it.

**Comment by playpauseandstop** [comment] 2020-01-29 23:12
@p1c2u 

Thanks for fixing this in `master`! 

I ran into similar issue of not having enough data about multiple validation errors, when for example several, not one, required fields is missing, and glad that soon I'll be able to get all schema errors, not the only first one.

**Comment by p1c2u** [comment] 2020-02-03 15:43
Duplicate of #160 hence closing

**Closed by p1c2u** 2020-02-03 15:43 UTC
