### ISSUE TITLE
Request Validation stops after first failure

### ISSUE THREAD

**Issue by riscmk** [p1c2u/openapi-core#108] opened 2019-02-18 08:13 UTC
The validator is working fine, but if there is more than one error in the data, the validate routine only raises the first error and stops validating the rest of the data.

This is quite frustrating, since you actually want to know all the errors in your dataset, and not just the first one.

Is there any way to prevent that (without overwriting a bunch of classes and methods of coruse)?

**Comment by berend** [comment] 2019-02-26 13:15
same as #100 I guess. I posted some more info in there.

**Comment by p1c2u** [comment] 2019-03-10 16:05
Duplicate of  #100

**Closed by p1c2u** 2019-03-10 16:05 UTC
Labels: resolution/duplicate
