### ISSUE TITLE
ImportError: cannot import name 'default_handlers' (0.14.2)

### ISSUE THREAD

**Issue by alanbchristie** [p1c2u/openapi-core#405] opened 2022-09-02 17:07 UTC
Suddenly started getting this error using `0.14.2`...

```python
>>> from openapi_core import create_spec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alan/opt/anaconda3/lib/python3.7/site-packages/openapi_core/__init__.py", line 3, in <module>
    from openapi_core.shortcuts import (
  File "/Users/alan/opt/anaconda3/lib/python3.7/site-packages/openapi_core/shortcuts.py", line 3, in <module>
    from openapi_core.spec.shortcuts import create_spec
  File "/Users/alan/opt/anaconda3/lib/python3.7/site-packages/openapi_core/spec/shortcuts.py", line 3, in <module>
    from openapi_spec_validator import (
ImportError: cannot import name 'default_handlers' from 'openapi_spec_validator' (/Users/alan/opt/anaconda3/lib/python3.7/site-packages/openapi_spec_validator/__init__.py)
```

I managed to get around the problem by updating to `0.14.4`

**Comment by p1c2u** [comment] 2022-09-02 17:24
Duplicate of #402 dance closing

**Closed by p1c2u** 2022-09-02 17:24 UTC
